site_name: Rok Popov Ledinski
site_description: Your site description
site_url: https://rokpopovledinski.com

nav:
  - Home:
    - About: index.md
  - Blog:
    - blog/index.md 
  - Success Stories:
    - Overview: portfolio/index.md
    - Projects:
      - portfolio/projects/ai-maddy.md
      - portfolio/projects/ai-coding-assistant.md
      - portfolio/projects/banking-ai-assistant.md
      - portfolio/projects/ai-planning-suite.md

theme:
  name: material
  features:
    - search.suggest
    - toc.integrate
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - content.tooltips
    - content.tabs.link
    - content.code.copy
    - navigation.footer
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: custom
      accent: custom  
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: custom
      accent: custom
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/slash-forward-box
  favicon: assets/favicon.png

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RokPopov
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@RokPopov
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rok-popov-ledinski/

extra_css:
  - stylesheets/extra.css
  - stylesheets/hero.css
plugins:
  - search
  - social:
      cards_layout_options:
        background_color: "#111111"
  - blog:
      blog_dir: blog
      authors_file: "{blog}/.authors.yml"
      categories: true

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.keys

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.1.0/js-yaml.min.js

copyright: |
  &copy; 2025 <a href="https://www.linkedin.com/in/rok-popov-ledinski/" target="_blank" rel="noopener">Rok Popov Ledinski</a>. All rights reserved.

name: Deploy Docs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: squidfunk/mkdocs-material:9.4.6
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          mkdocs build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4