authors:
  rokpopovledinski:
    name: Rok Popov Ledinski
    description: AI Engineer & Applied Consultant
    avatar: https://avatars.githubusercontent.com/u/59090063?v=4
    url: https://www.linkedin.com/in/rok-popov-ledinski/