name: Deploy Docs
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install MkDocs Material with all extensions
          pip install "mkdocs-material==9.1.15"
          pip install "mkdocs-material-extensions==1.1.1"
          # Install other required packages
          pip install "pymdown-extensions>=10.0"
          pip install "pygments>=2.14"
          pip install "cairosvg==2.5.2" "pillow==9.4.0"
      - name: Fix Google Fonts
        run: |
          # Create cache directories
          mkdir -p .cache/plugin/social
          # Download fonts manually
          curl -sfSL "https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" > /dev/null
          curl -sfSL "https://fonts.gstatic.com/s/roboto/v30/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf" -o .cache/plugin/social/roboto-regular.ttf
          curl -sfSL "https://fonts.gstatic.com/s/roboto/v30/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf" -o .cache/plugin/social/roboto-bold.ttf
      - name: Build
        run: mkdocs build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4